filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/app.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    json.overwrite_keys: true

setup.template.enabled: false
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"

logging.level: info